program: /home/julien/Documents/BenchMARL/benchmarl/run.py
project: "benchmarl"
entity: "julien-soule-university-of-luxembourg"

method: bayes 

metric:
  name: eval/agents/reward/episode_reward_mean
  goal: maximize

parameters:

  # experiment hyperparameters 

  experiment.lr:
    max: 0.003
    min: 0.000025
    # distribution: uniform

  experiment.on_policy_n_minibatch_iters:
    values: [1, 2]

  experiment.on_policy_minibatch_size:
    values: [64, 128, 256]

  # algorithm hyperparameters 
  algorithm.entropy_coef:
      max: 0.05
      min: 0
      distribution: uniform

  task:
    value: "vmas/balance"

  algorithm:
    value: "mappo"
        
early_terminate:
  type: hyperband
  max_iter: 27
  s: 3
  # seed:
  #   max: 84
  #   min: 0
  #   distribution: int_uniform

command:
  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens}
  
